### ISSUE TITLE
beta Roadmap

### ISSUE THREAD

**Issue by skerkour** [skerkour/black-hat-rust#25]
See [here for the Changelog](https://github.com/skerkour/black-hat-rust/blob/main/CHANGELOG.md).

- [x] Fri 29/10: ch01 - v2021.24
    - [x] review illustrations
    - [x] fill "coming soon"
    - [x] edit
    - [x] typos
- [x] Tue 02/11: ch02 - v2021.25
    - [x] review illustrations
    - [x] fill "coming soon"
    - [x] edit
    - [x] typos
- [x] Sat 06/11: ch03 - v2021.26
    - [x] review illustrations
    - [x] fill "coming soon"
    - [x] edit
    - [x] typos
- [x] Sun 07/11: ch11 - v2021.27
    - [x] review illustrations
    - [x] fill "coming soon"
    - [x] edit
    - [x] typos
- [x] Mon 08/11: ch13 - v2021.28
    - [x] review illustrations
    - [x] fill "coming soon"
    - [x] edit
    - [x] typos
- [x] Mon 08/11: ch14 - v2021.29
    - [x] review illustrations
    - [x] fill "coming soon"
    - [x] edit
    - [x] typos
- [x] Tue 09/11: ch08 - v2021.30
    - [x] review illustrations
    - [x] fill "coming soon"
    - [x] edit
    - [x] typos
 - [x] Wed 10/11: ch10 - v2021.31
    - [x] review illustrations
    - [x] fill "coming soon"
    - [x] edit
    - [x] typos
- [x] Thu 11/11: ch04 - v2021.32
    - [x] review illustrations
    - [x] fill "coming soon"
    - [x] edit
    - [x] typos
- [x] Fri 12/11: ch12 - v2021.33
    - [x] review illustrations
    - [x] fill "coming soon"
    - [x] edit
    - [x] typos
- [x] Sat 13/11: ch06 - v2021.34
    - [x] review illustrations
    - [x] fill "coming soon"
    - [x] edit
    - [x] typos
- [x] Mon 15/11: ch05 - v2021.35
    - [x] review illustrations
    - [x] fill "coming soon"
    - [x] edit
    - [x] typos
- [x] Tue 16/11: ch07 - v2021.36
    - [x] review illustrations
    - [x] fill "coming soon"
    - [x] edit
    - [x] typos
 - [x] Thu 18/11: ch09 - v2021.37
    - [x] review illustrations
    - [x] fill "coming soon"
    - [x] edit
    - [x] typos
